# Form implementation generated from reading ui file 'C:\Users\hoduc\PycharmProjects\BVGD_Project\src\app\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(1366, 768)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        mainWidget.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(mainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=mainWidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_kham_benh = QtWidgets.QWidget()
        self.tab_kham_benh.setObjectName("tab_kham_benh")
        self.tabWidget.addTab(self.tab_kham_benh, "")
        self.tab_dkdv = QtWidgets.QWidget()
        self.tab_dkdv.setObjectName("tab_dkdv")
        self.tabWidget.addTab(self.tab_dkdv, "")
        self.tab_tai_vu = QtWidgets.QWidget()
        self.tab_tai_vu.setObjectName("tab_tai_vu")
        self.tabWidget.addTab(self.tab_tai_vu, "")
        self.tab_tiep_nhan = QtWidgets.QWidget()
        self.tab_tiep_nhan.setObjectName("tab_tiep_nhan")
        self.tabWidget.addTab(self.tab_tiep_nhan, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(mainWidget)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "Phần mềm quản lý bệnh viện"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_kham_benh), _translate("mainWidget", "Khám bệnh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dkdv), _translate("mainWidget", "Đăng ký dịch vụ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tai_vu), _translate("mainWidget", "Tài vụ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tiep_nhan), _translate("mainWidget", "Tiếp nhận"))
